# Generated by Django 2.2.4 on 2019-08-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('presentacion', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=15)),
                ('pre_venta', models.IntegerField()),
                ('pre_compra', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.CharField(max_length=10)),
                ('cod_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
                ('cod_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentacion.Presentacion')),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
        ),
    ]
