# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenpedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='cod_tipo_pago',
            field=models.CharField(max_length=10),
        ),
    ]
