# Generated by Django 2.2.4 on 2019-08-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=15)),
                ('dir_proveedor', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=12)),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrito.Distrito')),
            ],
        ),
    ]
