# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': set([('proveedor_permission', 'Usuario proveedor')])},
        ),
    ]
