# Generated by Django 2.2.4 on 2019-08-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cod_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cliente', models.CharField(max_length=15)),
                ('dir_cliente', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=10)),
                ('ruc', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=12)),
                ('cod_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distrito.Distrito')),
            ],
        ),
    ]
