# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0002_auto_20190812_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.EmailField(max_length=254),
        ),
    ]
