# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20190812_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': set([('empleado_permission', 'Usuario empleado')])},
        ),
    ]
