# Generated by Django 2.2.4 on 2019-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=10)),
            ],
        ),
    ]
